### ISSUE TITLE
Change Library References

### ISSUE THREAD

**Issue by quickfeet14** [shurik179/pov-esp32#1]
POV4.1.ino is asking for pov-esp32.h, this library here is still labelled pov.h which causes a compile error when trying to upload. Need to update the name and references so it pulls in the correct library for ESP32 devices.

**Comment by shurik179** [comment]
Indeed, you are quite right. 
There is a lto more that needs to be fixed, but I will at least fix this issue  shortly.

**Comment by shurik179** [comment]
Done
